[package]
name = "futil-site"
version = "0.1.0"
authors = ["Samuel Thomas <sgt43@cornell.edu>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
calyx = { git = "https://github.com/cucapra/futil.git", branch = "calyx_lib" }
sexpy = "~0.5"
wasm-bindgen = "0.2"
